chore: fix integration tests workflow

diff --git a/.github/workflows/integration-tests.yml b/.github/workflows/integration-tests.yml
--- a/.github/workflows/integration-tests.yml
+++ b/.github/workflows/integration-tests.yml
@@ -73,8 +73,8 @@ jobs:
             ((attempt++))
           else
             echo "k8ssandra-operator pod status: $phase"
-            cass_operator_pod=$(kubectl get pods -l app.kubernetes.io/name=k8ssandra-operator -n ${{ env.cassandra_namespace }})
-            kubectl get events -n ${{ env.cassandra_namespace }} --for pod/"$cass_operator_pod"
+            cass_operator_pod=$(kubectl get pods -l app.kubernetes.io/name=k8ssandra-operator -n ${{ env.cassandra_namespace }} -o jsonpath='{.items[0]}' -o custom-columns=":metadata.name" --no-headers)
+            kubectl events -n ${{ env.cassandra_namespace }} --for pod/"$cass_operator_pod"
             exit 1
           fi
         done
@@ -123,7 +123,7 @@ jobs:
           echo "Attempt $attempt/$max_attempts: Checking k8ssandra cluster status..."
           phase=$(kubectl get pod -l app.kubernetes.io/name=cassandra -n ${{ env.cassandra_namespace }} -o jsonpath='{.items[0].status.phase}' 2>/dev/null || echo "NotFound")
           ready=$(kubectl get pod -l app.kubernetes.io/name=cassandra -n ${{ env.cassandra_namespace }} -o jsonpath='{.items[0].status.conditions[?(@.type=="Ready")].status}' 2>/dev/null || echo "NotFound")
-          scheduled=$(kubectl get pod -l app.kubernetes.io/name=cassandra -n -n ${{ env.cassandra_namespace }} -o jsonpath='{.items[0].status.conditions[?(@.type=="PodScheduled")].status}' 2>/dev/null || echo "SchedulingError")
+          scheduled=$(kubectl get pod -l app.kubernetes.io/name=cassandra -n ${{ env.cassandra_namespace }} -o jsonpath='{.items[0].status.conditions[?(@.type=="PodScheduled")].status}' 2>/dev/null || echo "SchedulingError")
           if [[ "$ready" == "True" ]]; then
             echo "k8ssandra cluster is ready."
             break
@@ -137,8 +137,8 @@ jobs:
             ((attempt++))
           else
             echo "k8ssandra cluster status: $phase"
-            cassandra_pod=$(kubectl get pods -l app.kubernetes.io/name=cassandra -n ${{ env.cassandra_namespace }})
-            kubectl get events -n ${{ env.cassandra_namespace }} --for pod/"$cassandra_pod"
+            cassandra_pod=$(kubectl get pod -l app.kubernetes.io/name=cassandra -n ${{ env.cassandra_namespace }} -o jsonpath='{.items[0]}' -o custom-columns=":metadata.name" --no-headers)
+            kubectl events -n ${{ env.cassandra_namespace }} --for pod/"$cassandra_pod"
             exit 1
           fi
         done
